apiVersion: v1
kind: Secret
metadata:
  name: chandra-db-secret
  labels:
    app: chandra-postgres-db
type: Opaque
data:
  POSTGRES_PASSWORD: Y2hhbmdlbWU
---
apiVersion: v1
kind: Service
metadata:
  name: register-app-db
  labels:
    app: register-app-db
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: chandra-postgres-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chandra-postgres-db
  labels:
    app: chandra-postgres-db
spec:
  serviceName: chandra-postgres-db
  replicas: 1
  selector:
    matchLabels:
      app: chandra-postgres-db
  template:
    metadata:
      labels:
        app: chandra-postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: registerdb
            - name: POSTGRES_USER
              value: register
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chandra-db-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
